name:                mtlstats
version:             0.0.0
github:              "mtlstats/mtlstats"
license:             BSD3
author:              "Jonathan Lamothe"
maintainer:          "jlamothe1980@gmail.com"
copyright:           "Rhéal Lamothe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/mtlstats#readme>

dependencies:
- base >= 4.7 && < 5
- microlens-th >= 0.4.2.3 && < 0.5
- microlens

library:
  source-dirs: src

executables:
  mtlstats-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlstats

tests:
  mtlstats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlstats
    - hspec >= 2.7.1 && < 2.8
