name:                mtlstats
version:             0.2.0
github:              "mtlstats/mtlstats"
license:             GPL-3
author:              "Jonathan Lamothe"
maintainer:          "jlamothe1980@gmail.com"
copyright:           "Rhéal Lamothe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/mtlstats#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.4.0 && < 1.5
- containers >= 0.6.0.1 && < 0.7
- easy-file >= 0.2.2 && < 0.3
- extra >= 1.6.17 && < 1.7
- microlens-th >= 0.4.2.3 && < 0.5
- ncurses >= 0.2.16 && < 0.3
- random >= 1.1 && < 1.2
- time >= 1.8.0.2 && < 1.9
- transformers >= 0.5.6.2 && < 0.6
- bytestring
- microlens

library:
  source-dirs: src

executables:
  mtlstats:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlstats

tests:
  mtlstats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlstats
    - hspec >= 2.7.1 && < 2.8
    - unordered-containers
